// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Rinku.Models
{
    public partial class Movimientos
    {
        public int Id { get; set; }
        public string NumEmpleado { get; set; }
        public int Mes { get; set; }
        public int CantidadEntregas { get; set; }
        public decimal? SueldoBruto { get; set; }
        public decimal? Isr { get; set; }
        public decimal? IsrAdicional { get; set; }
        public decimal? Vales { get; set; }
        public decimal? SueldoNeto { get; set; }
    }
}